### ISSUE TITLE
Sitting Ducks support?

### ISSUE THREAD

**Issue by SonikkuA-DatH** [widberg/dpc#22]
I haven't tried the tool yet, though given most games listed in README are after Version 1.38xx, while Sitting Ducks is 1.19(PS2) or 1.22(PC), I have doubts

I'll close this issue if there are no problems

**Comment by widberg** [comment]
Check out https://github.com/chebureki/DuckHax-CLI. All of my development for the BigFile format has moved to https://github.com/widberg/bff. I should just archive this repository.
