### ISSUE TITLE
Export DPC file error

### ISSUE THREAD

**Issue by Sauong** [widberg/dpc#7]
Export file error please help me : (example : https://www.mediafire.com/file/supisz9sisi9j85/example.rar/file )
Error : 0/616 thread 'main' panicked at 'Parsing requires 4 bytes/chars on block 1', src\fuel_dpc.rs:452:31

**Comment by widberg** [comment]
Hello, thank you for checking out the tool.  Unfortunately that looks like a "A Plague Tale: Innocence" DPC file judging from the version "v2.128.92.19 - Asobo Studio - Internal Cross Technology". The README lists the supported games and "A Plague Tale: Innocence"  is not one of them. You are welcome to submit a pull request adding support for this version of the format but I am unlikely to add it myself soon.
