### ISSUE TITLE
A Plague Tale

### ISSUE THREAD

**Issue by MeblIkea** [widberg/dpc#9]
Hi, how to get files from A Plague Tale Innocence or Requiem please?

**Comment by widberg** [comment]
Sorry, this tool does not work on those games. The format has changed quite a bit since the games that this was made for.

**Comment by MeblIkea** [comment]
Hi, thanks for your answer. I managed to find a tool, and it works kinda =)
https://github.com/amrshaheen61/APT_DPC_Tool

**Comment by widberg** [comment]
I recommend checking out
[TotemTech Modding Resources](https://github.com/widberg/fmtk/wiki/TotemTech-Modding-Resources) (specifically the Tutorials)
[Reverse Engineering Tools](https://github.com/widberg/fmtk/wiki/Reverse-Engineering-Tools)
